# Generated by Django 4.2.5 on 2023-09-14 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittlelemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='iventory',
            new_name='inventory',
        ),
    ]
